
version: 2

models:
  - name: stg_matchlogs__all
    description: "All raw matchlogs from FBref.com"    
    tags: ["staging", "fbref", "goalkeepers"]
    meta:
      grain: "goalkeeper-match"
      source: "FBref.com"
    columns:
      - name: source_table
        description: "Metadata column of the form <player_slug>_<season>"
        tests:
          - not_null
      - name: date
        description: "Match date"
      - name: dayofweek
        description: "Day of the week football match took place"
      - name: comp
        description: "Competiton football match was played under"
      - name: round
        description: "Round of the football match competition"
      - name: venue
        description: "Venue of the football match relative to the home team"
      - name: result
        description: "Outcome and scoreline of the football match"
      - name: team
        description: "Team the goalkeeper was playing for"
      - name: opponent
        description: "Opponent the goalkeeper was playing against"
      - name: game_started
        description: "Flag to indicate whether goalkeeper played or not"
      - name: position
        description: "Position goalkeeper played in"
      - name: minutes
        description: "Number of minutes goalkeeper played for"
      - name: gk_shots_on_target_against
        description: "Nunmber of shots faced by goalkeeper during the match"
      - name: gk_goals_against
        description: "Number of goals conceded by goalkeeper during the match"
      - name: gk_saves
        description: "Number of saves made by goalkeeper during the match"
      - name: gk_save_pct
        description: "Save percentage for the goalkeeper for the match"
      - name: gk_clean_sheets
        description: "Flag to indicate whether goalkeeper kept a clean sheet"
      - name: gk_psxg
        description: "Post-Shot Expected Goals"
      - name: gk_pens_att
        description: "Penalty kicks faced"
      - name: gk_pens_allowed
        description: "Penalty kicks conceded"
      - name: gk_pens_saved
        description: "Penalty kicks saved"
      - name: gk_pens_missed
        description: "(to add)"
      - name: gk_passes_completed_launched
        description: "Passes more than 40 yards completed"
      - name: gk_passes_launched
        description: "Passes more than 40 yards attempted"
      - name: gk_passes_pct_launched
        description: "Pass completion % for passed more than 40 yards"
      - name: gk_passes
        description: "Passes attempted (not including goal kicks)"
      - name: gk_passes_throws
        description: "Throws attempted"
      - name: gk_pct_passes_launched
        description: "Pct. of passes launched (> 40 yds) excluding goal kicks"
      - name: gk_passes_length_avg
        description: "Average length of passes in yards excluding goal kicks"
      - name: gk_goal_kicks
        description: "Goal kicks attempted"
      - name: gk_pct_goal_kicks_launched
        description: "Pct. of goal kicks that were launched (> 40 yds)"
      - name: gk_goal_kick_length_avg
        description: "Average length of goal kicks in yards"
      - name: gk_crosses
        description: "Opponents attempted crosses into the penalty area"
      - name: gk_crosses_stopped
        description: "Crosses into the penalty area successfully stopped"
      - name: gk_crosses_stopped_pct
        description: "Pct. of crosses into penalty area successfully stopped"
      - name: gk_def_actions_outside_pen_area
        description: "Numebr of defensive actions outside penalty area"
      - name: gk_avg_distance_def_actions
        description: "Avg. distance from goal (yards) of all defensive actions"
      - name: match_report
        description: "Hyperlink to match report (quirk from ingestion step)"
