
select
    source_table,
    regexp_replace(source_table, '_[0-9]{4}_[0-9]{4}$', '') as goalkeeper,
    regexp_extract(source_table, '([0-9]{4}_[0-9]{4})$', 1) as season,
    date AS match_date,
    comp AS competition,    
    round,
    venue,
    result,
    team, 
    opponent,
    game_started,
    minutes AS minutes_played,
    gk_shots_on_target_against,
    gk_goals_against,
    gk_saves,
    gk_clean_sheets,
    gk_psxg,
    gk_pens_att,
    gk_pens_allowed,
    gk_pens_saved,
    gk_pens_missed,
    gk_passes_launched,
    gk_passes_completed_launched,
    gk_passes,    
    gk_passes_throws,
    gk_passes_length_avg,
    gk_goal_kicks, 
    gk_goal_kicks * gk_pct_goal_kicks_launched AS gk_goal_kicks_launched,
    gk_goal_kick_length_avg,
    gk_crosses,
    gk_crosses_stopped,
    gk_def_actions_outside_pen_area,
    gk_avg_distance_def_actions

from {{ ref('stg_matchlogs__all') }}
